"""fix_user_ondelete_cascades

Revision ID: 8f215b5a651b
Revises: e421859e49b1
Create Date: 2026-06-14 14:27:40.346460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f215b5a651b'
down_revision: Union[str, Sequence[str], None] = 'e421859e49b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_invites', 'invited_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('org_invites_invited_by_fkey'), 'org_invites', type_='foreignkey')
    op.drop_constraint(op.f('org_invites_revoked_by_fkey'), 'org_invites', type_='foreignkey')
    op.drop_constraint(op.f('org_invites_accepted_by_fkey'), 'org_invites', type_='foreignkey')
    op.create_foreign_key(None, 'org_invites', 'users', ['revoked_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'org_invites', 'users', ['accepted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'org_invites', 'users', ['invited_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'org_invites', type_='foreignkey')
    op.drop_constraint(None, 'org_invites', type_='foreignkey')
    op.drop_constraint(None, 'org_invites', type_='foreignkey')
    op.create_foreign_key(op.f('org_invites_accepted_by_fkey'), 'org_invites', 'users', ['accepted_by'], ['id'])
    op.create_foreign_key(op.f('org_invites_revoked_by_fkey'), 'org_invites', 'users', ['revoked_by'], ['id'])
    op.create_foreign_key(op.f('org_invites_invited_by_fkey'), 'org_invites', 'users', ['invited_by'], ['id'])
    op.alter_column('org_invites', 'invited_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
