"""Initial schema

Revision ID: d06281cb4bdb
Revises: 
Create Date: 2026-06-11 00:13:18.343570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd06281cb4bdb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create extensions first
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_repos', sa.Integer(), nullable=False),
    sa.Column('max_credentials', sa.Integer(), nullable=False),
    sa.Column('allow_slack', sa.Boolean(), nullable=False),
    sa.Column('allow_multi_llm', sa.Boolean(), nullable=False),
    sa.Column('allow_audit_export', sa.Boolean(), nullable=False),
    sa.Column('price_usd_monthly', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('organisations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('plan_tier_id', sa.Integer(), nullable=False),
    sa.Column('plan_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('billing_email', postgresql.CITEXT(), nullable=True),
    sa.Column('billing_name', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspension_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_tier_id'], ['plan_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_orgs_active', 'organisations', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_orgs_slug', 'organisations', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('can_access_admin_portal', sa.Boolean(), nullable=False),
    sa.Column('can_access_user_portal', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_invited', sa.Boolean(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'email', name='users_org_id_email_key'),
    sa.UniqueConstraint('org_id', 'username', name='users_org_id_username_key')
    )
    op.create_index('idx_users_active', 'users', ['org_id', 'is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_users_admin', 'users', ['org_id'], unique=False, postgresql_where=sa.text("role IN ('owner', 'admin') AND is_active = true"))
    op.create_index('idx_users_email', 'users', ['org_id', 'email'], unique=False)
    op.create_index('idx_users_org', 'users', ['org_id'], unique=False)
    op.create_table('agent_settings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('dangerous_actions_require_confirm', sa.Boolean(), nullable=False),
    sa.Column('confirmation_token', sa.Text(), nullable=False),
    sa.Column('safe_workspace_root', sa.Text(), nullable=False),
    sa.Column('allowed_shell_prefixes', postgresql.ARRAY(sa.Text()), server_default=sa.text("ARRAY['ls','dir','pwd','echo','cat','type']::text[]"), nullable=False),
    sa.Column('max_shell_output_chars', sa.Integer(), nullable=False),
    sa.Column('tool_rate_limit_count', sa.Integer(), nullable=False),
    sa.Column('tool_rate_limit_window_secs', sa.Integer(), nullable=False),
    sa.Column('log_level', sa.Text(), nullable=False),
    sa.Column('audit_log_retention_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('log_source', sa.String(), nullable=False),
    sa.Column('tool', sa.Text(), nullable=True),
    sa.Column('allowed', sa.Boolean(), nullable=True),
    sa.Column('tool_reason', sa.Text(), nullable=True),
    sa.Column('http_method', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('auth_event', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_auth', 'audit_logs', ['org_id', 'auth_event', sa.literal_column('ts DESC')], unique=False, postgresql_where=sa.text('auth_event IS NOT NULL'))
    op.create_index('idx_audit_blocked', 'audit_logs', ['org_id', sa.literal_column('ts DESC')], unique=False, postgresql_where=sa.text('allowed = false'))
    op.create_index('idx_audit_org_ts', 'audit_logs', ['org_id', sa.literal_column('ts DESC')], unique=False)
    op.create_index('idx_audit_tool', 'audit_logs', ['org_id', 'tool', sa.literal_column('ts DESC')], unique=False, postgresql_where=sa.text('tool IS NOT NULL'))
    op.create_index('idx_audit_user', 'audit_logs', ['org_id', 'user_id', sa.literal_column('ts DESC')], unique=False, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('llm_provider_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('api_key_hint', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_tool_steps', sa.Integer(), nullable=False),
    sa.Column('max_history', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(), nullable=False),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'provider', 'label', name='llm_provider_configs_org_id_provider_label_key')
    )
    op.create_index('idx_llm_one_default', 'llm_provider_configs', ['org_id', 'provider'], unique=True, postgresql_where=sa.text('is_default = true AND is_active = true'))
    op.create_table('oauth_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.Text(), nullable=False),
    sa.Column('provider_username', sa.Text(), nullable=True),
    sa.Column('provider_email', sa.Text(), nullable=True),
    sa.Column('provider_avatar_url', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='oauth_connections_provider_provider_user_id_key')
    )
    op.create_index('idx_oauth_provider', 'oauth_connections', ['provider', 'provider_user_id'], unique=False)
    op.create_index('idx_oauth_user', 'oauth_connections', ['user_id'], unique=False)
    op.create_table('org_invites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('invited_email', postgresql.CITEXT(), nullable=False),
    sa.Column('assigned_role', sa.String(), nullable=False),
    sa.Column('invite_note', sa.Text(), nullable=True),
    sa.Column('invite_code', sa.Text(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code')
    )
    op.create_index('idx_invites_code', 'org_invites', ['invite_code'], unique=False, postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.create_index('idx_invites_org', 'org_invites', ['org_id'], unique=False, postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.create_table('platform_credentials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=True),
    sa.Column('github_owner', sa.Text(), nullable=True),
    sa.Column('github_app_id', sa.Text(), nullable=True),
    sa.Column('gitlab_group_id', sa.Text(), nullable=True),
    sa.Column('jenkins_username', sa.Text(), nullable=True),
    sa.Column('azure_organisation', sa.Text(), nullable=True),
    sa.Column('azure_project', sa.Text(), nullable=True),
    sa.Column('token_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('token_hint', sa.Text(), nullable=True),
    sa.Column('token_scopes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(), nullable=False),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'platform', 'label', name='platform_credentials_org_id_platform_label_key')
    )
    op.create_index('idx_creds_expiry', 'platform_credentials', ['token_expires_at'], unique=False, postgresql_where=sa.text('token_expires_at IS NOT NULL AND is_active = true'))
    op.create_index('idx_creds_org', 'platform_credentials', ['org_id', 'platform'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('family_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('portal', sa.Text(), nullable=False),
    sa.Column('device_label', sa.Text(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotation_count', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_rt_cleanup', 'refresh_tokens', ['expires_at'], unique=False, postgresql_where=sa.text('is_revoked = false'))
    op.create_index('idx_rt_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index('idx_rt_token_hash', 'refresh_tokens', ['token_hash'], unique=False, postgresql_where=sa.text('is_revoked = false'))
    op.create_index('idx_rt_user_active', 'refresh_tokens', ['user_id', 'expires_at'], unique=False, postgresql_where=sa.text('is_revoked = false'))
    op.create_table('slack_configs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('slack_workspace_id', sa.Text(), nullable=True),
    sa.Column('slack_workspace_name', sa.Text(), nullable=True),
    sa.Column('bot_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('app_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('bot_token_hint', sa.Text(), nullable=True),
    sa.Column('app_token_hint', sa.Text(), nullable=True),
    sa.Column('default_alert_channel', sa.Text(), nullable=True),
    sa.Column('allowed_channel', sa.Text(), nullable=True),
    sa.Column('require_mention', sa.Boolean(), nullable=False),
    sa.Column('max_reply_chars', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_test_status', sa.String(), nullable=False),
    sa.Column('last_test_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('verification_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('idx_vt_user_purpose', 'verification_tokens', ['user_id', 'purpose'], unique=False, postgresql_where=sa.text('used_at IS NULL'))
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('credential_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monitor_enabled', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_secs', sa.Integer(), nullable=False),
    sa.Column('notify_slack', sa.Boolean(), nullable=False),
    sa.Column('slack_channel', sa.Text(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_poll_status', sa.Text(), nullable=True),
    sa.Column('last_poll_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['credential_id'], ['platform_credentials.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'platform', 'name', name='repositories_org_id_platform_name_key')
    )
    op.create_index('idx_repos_credential', 'repositories', ['credential_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_repos_org_active', 'repositories', ['org_id'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_repos_poll_due', 'repositories', ['last_polled_at'], unique=False, postgresql_where=sa.text('is_active = true AND monitor_enabled = true'))
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('triggered_by', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('repo_name', sa.Text(), nullable=False),
    sa.Column('job_name', sa.Text(), nullable=True),
    sa.Column('trigger_event', sa.Text(), nullable=True),
    sa.Column('run_id', sa.Text(), nullable=True),
    sa.Column('run_url', sa.Text(), nullable=True),
    sa.Column('log_snippet', sa.Text(), nullable=True),
    sa.Column('full_log_size_bytes', sa.Integer(), nullable=True),
    sa.Column('log_hash', sa.Text(), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('analysis_tokens', sa.Integer(), nullable=True),
    sa.Column('llm_config_id', sa.UUID(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_model', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['llm_config_id'], ['llm_provider_configs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analysis_active', 'analysis_results', ['org_id', 'status'], unique=False, postgresql_where=sa.text("status IN ('pending', 'streaming')"))
    op.create_index('idx_analysis_log_hash', 'analysis_results', ['org_id', 'log_hash'], unique=False, postgresql_where=sa.text('log_hash IS NOT NULL'))
    op.create_index('idx_analysis_org_recent', 'analysis_results', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_analysis_repo', 'analysis_results', ['org_id', 'repo_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('seen_failures',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('repo_name', sa.Text(), nullable=False),
    sa.Column('run_id', sa.Text(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'platform', 'repo_name', 'run_id', name='seen_failures_org_platform_repo_run_key')
    )
    op.create_index('idx_seen_failures_lookup', 'seen_failures', ['org_id', 'platform', 'repo_name'], unique=False)
    op.create_index('idx_seen_failures_recent', 'seen_failures', ['org_id', sa.literal_column('detected_at DESC')], unique=False)
    # ### end Alembic commands ###

    # Seed plan_tiers
    op.execute("""
    INSERT INTO plan_tiers
        (name, display_name, max_users, max_repos, max_credentials, allow_slack, allow_multi_llm, allow_audit_export, price_usd_monthly, is_active)
    VALUES
        ('free',       'Free',        3,   5,   2,   false, false, false,  0.00, true),
        ('pro',        'Pro',         15,  25,  10,  true,  true,  true,   49.00, true),
        ('enterprise', 'Enterprise',  999, 999, 999, true,  true,  true,  199.00, true);
    """)

    # Create triggers and functions
    op.execute("""
    CREATE OR REPLACE FUNCTION fn_sync_portal_access()
    RETURNS TRIGGER LANGUAGE plpgsql AS $$
    BEGIN
        NEW.can_access_admin_portal := NEW.role IN ('owner', 'admin');
        NEW.can_access_user_portal  := true;
        RETURN NEW;
    END;
    $$;
    """)

    op.execute("""
    CREATE TRIGGER trg_users_sync_portal_access
        BEFORE INSERT OR UPDATE OF role ON users
        FOR EACH ROW EXECUTE FUNCTION fn_sync_portal_access();
    """)

    op.execute("""
    CREATE OR REPLACE FUNCTION fn_set_updated_at()
    RETURNS TRIGGER LANGUAGE plpgsql AS $$
    BEGIN
        NEW.updated_at = now();
        RETURN NEW;
    END;
    $$;
    """)

    for table in ['organisations', 'users', 'oauth_connections', 'platform_credentials', 'llm_provider_configs', 'slack_configs', 'repositories']:
        op.execute(f"""
        CREATE TRIGGER trg_updated_at_{table}
            BEFORE UPDATE ON {table}
            FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at();
        """)



def downgrade() -> None:
    """Downgrade schema."""
    # Drop custom triggers and functions
    for table in ['organisations', 'users', 'oauth_connections', 'platform_credentials', 'llm_provider_configs', 'slack_configs', 'repositories']:
        op.execute(f"DROP TRIGGER IF EXISTS trg_updated_at_{table} ON {table}")
        
    op.execute("DROP TRIGGER IF EXISTS trg_users_sync_portal_access ON users")
    op.execute("DROP FUNCTION IF EXISTS fn_sync_portal_access()")
    op.execute("DROP FUNCTION IF EXISTS fn_set_updated_at()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_seen_failures_recent', table_name='seen_failures')
    op.drop_index('idx_seen_failures_lookup', table_name='seen_failures')
    op.drop_table('seen_failures')
    op.drop_index('idx_analysis_repo', table_name='analysis_results')
    op.drop_index('idx_analysis_org_recent', table_name='analysis_results')
    op.drop_index('idx_analysis_log_hash', table_name='analysis_results', postgresql_where=sa.text('log_hash IS NOT NULL'))
    op.drop_index('idx_analysis_active', table_name='analysis_results', postgresql_where=sa.text("status IN ('pending', 'streaming')"))
    op.drop_table('analysis_results')
    op.drop_index('idx_repos_poll_due', table_name='repositories', postgresql_where=sa.text('is_active = true AND monitor_enabled = true'))
    op.drop_index('idx_repos_org_active', table_name='repositories', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_repos_credential', table_name='repositories', postgresql_where=sa.text('is_active = true'))
    op.drop_table('repositories')
    op.drop_index('idx_vt_user_purpose', table_name='verification_tokens', postgresql_where=sa.text('used_at IS NULL'))
    op.drop_table('verification_tokens')
    op.drop_table('slack_configs')
    op.drop_index('idx_rt_user_active', table_name='refresh_tokens', postgresql_where=sa.text('is_revoked = false'))
    op.drop_index('idx_rt_token_hash', table_name='refresh_tokens', postgresql_where=sa.text('is_revoked = false'))
    op.drop_index('idx_rt_family', table_name='refresh_tokens')
    op.drop_index('idx_rt_cleanup', table_name='refresh_tokens', postgresql_where=sa.text('is_revoked = false'))
    op.drop_table('refresh_tokens')
    op.drop_index('idx_creds_org', table_name='platform_credentials', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_creds_expiry', table_name='platform_credentials', postgresql_where=sa.text('token_expires_at IS NOT NULL AND is_active = true'))
    op.drop_table('platform_credentials')
    op.drop_index('idx_invites_org', table_name='org_invites', postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.drop_index('idx_invites_code', table_name='org_invites', postgresql_where=sa.text('accepted_at IS NULL AND revoked_at IS NULL'))
    op.drop_table('org_invites')
    op.drop_index('idx_oauth_user', table_name='oauth_connections')
    op.drop_index('idx_oauth_provider', table_name='oauth_connections')
    op.drop_table('oauth_connections')
    op.drop_index('idx_llm_one_default', table_name='llm_provider_configs', postgresql_where=sa.text('is_default = true AND is_active = true'))
    op.drop_table('llm_provider_configs')
    op.drop_index('idx_audit_user', table_name='audit_logs', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_audit_tool', table_name='audit_logs', postgresql_where=sa.text('tool IS NOT NULL'))
    op.drop_index('idx_audit_org_ts', table_name='audit_logs')
    op.drop_index('idx_audit_blocked', table_name='audit_logs', postgresql_where=sa.text('allowed = false'))
    op.drop_index('idx_audit_auth', table_name='audit_logs', postgresql_where=sa.text('auth_event IS NOT NULL'))
    op.drop_table('audit_logs')
    op.drop_table('agent_settings')
    op.drop_index('idx_users_org', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_admin', table_name='users', postgresql_where=sa.text("role IN ('owner', 'admin') AND is_active = true"))
    op.drop_index('idx_users_active', table_name='users', postgresql_where=sa.text('is_active = true'))
    op.drop_table('users')
    op.drop_index('idx_orgs_slug', table_name='organisations')
    op.drop_index('idx_orgs_active', table_name='organisations', postgresql_where=sa.text('is_active = true'))
    op.drop_table('organisations')
    op.drop_table('plan_tiers')
    
    # Drop extensions if needed
    op.execute('DROP EXTENSION IF EXISTS "citext"')
    op.execute('DROP EXTENSION IF EXISTS "pgcrypto"')
    # ### end Alembic commands ###
