"""add_first_name_last_name_to_users

Revision ID: e421859e49b1
Revises: e15f2dc87e6a
Create Date: 2026-06-14 13:32:02.177773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e421859e49b1'
down_revision: Union[str, Sequence[str], None] = 'e15f2dc87e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('org_invites', 'invited_email',
               existing_type=postgresql.CITEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('organisations', 'billing_email',
               existing_type=postgresql.CITEXT(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('users', sa.Column('first_name', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.Text(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=postgresql.CITEXT(),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.Text(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.alter_column('organisations', 'billing_email',
               existing_type=sa.Text(),
               type_=postgresql.CITEXT(),
               existing_nullable=True)
    op.alter_column('org_invites', 'invited_email',
               existing_type=sa.Text(),
               type_=postgresql.CITEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
